Repository upfluence/pkg, pull requests merged in 2021-01, with the labels that each got.

#33 intervalpush/: Make the exporter cleanly stopable.
  prometheus/exporter/exporter.go
  prometheus/exporter/intervalpush/exporter.go
  thrift/serializer/struct_test.go
Labels: enhancement, reviewed/needs-review

#34 Add exporter constructor with options
  .circleci/config.yml
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  prometheus/exporter/intervalpush/exporter.go
Labels: enhancement, reviewed/ready-to-merge

#35 Fix test flakiness is syncutil
  syncutil/singleflight_test.go
Labels: bug, reviewed/ready-to-merge
